### ISSUE TITLE
[BCC] v1.5 error in Sethekk Halls normal

### ISSUE THREAD

**Issue by Road-block** [a-vasilev/classic-loca#3]
This happens when Time-Lost Controller summons a Charming Totem which then proceeds to mind-control a player.

This is in normal difficulty, might be an issue with mind-controls from summoned minions or controls that have no expiration until the npc is killed, in general, but haven't had a chance to test elsewhere.

Relevant NPCs and spells.

- [Time-Lost Controller](https://tbc.wowhead.com/npc=18327)
- [Summon Charming Totem](https://tbc.wowhead.com/spell=32764)
- [Charming Totem](https://tbc.wowhead.com/npc=20343)
- [Charm](https://tbc.wowhead.com/spell=35120) ◀️ this is the effect that causes the error

```
1x LoCA\Modules\Debuffs.lua:509: attempt to perform arithmetic on field 'timeLeft' (a nil value)
[string "@LoCA\Modules\Debuffs.lua"]:509: in function 'ActivateNewDebuff'
[string "@LoCA\Modules\Debuffs.lua"]:255: in function 'OnLossOfControlEvent'
[string "@LoCA\Modules\Debuffs.lua"]:265: in function 'OnLossOfControlUpdate'
[string "@LoCA\LoCA-1.5.lua"]:162: in function <LoCA\LoCA.lua:148>
```

**Comment by a-vasilev** [comment]
Thanks a lot for the report, this issue has been a pain to fix :D I've been incrementally fixing different scenarios thanks to reports like this, because it's kind of annoying to go and reproduce it in the dungeon.

I'm deploying a new version which should fix this case. I'll wait a few days to see if any other reports turn up, if not then I'll close the issue

**Comment by Road-block** [comment]
I'll take a look at the source maybe I can contribute something.  
The ideal behavior from a player perspective would be for crowd control with potentially infinite duration (or at least undefined duration) to still show up but get removed when that debuff drops off the player.

**Comment by a-vasilev** [comment]
Yeah, that's what should be happening, but I just wasn't checking whether the duration of the control effect was nil, so whenever a nil one would come it threw the error.
